name: static test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v ./internal/app